KS-20-5 Пятое задание выполнено
Hudzone/Hudz.three pull request #102
Opened 2024-08-13 17:46 UTC by Hudzone

2024-08-14 07:18 UTC, ievetrovdev requested changes

2024-08-14 07:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_20/Task_5.kt
> +    fun sayModifier() {
По ТЗ  Модификатор устанавливается функцией setModifier(), принимающей лямбду.
Это значит что модификатор мы задаем с помощью метода в не класса(из мейна), а потом уже в  say() его используем

2024-08-15 07:37 UTC, ievetrovdev requested changes
Смотри, надо чтобы сам класс хранит лямбду как переменную, а в методе setModifier мы будем передавать лямбду которую создали в мейне. Сама лярду будет принимать не класс работа, а строку(фразу). метод say будет использовать эту лямбду перед выводом строки

2024-08-15 17:04 UTC, Hudzone commented
Не сразу понял, как правильно сделать, спасибо за подсказки, вроде сейчас верно.

Изменения:
- создал переменную для лямбды, нулабельную, чтобы в методе say можно было воспользоваться элвис оператором, этим заменил if-else конструкцию
- создал функцию, которая принимает лямбду, которая в свою очередь принимает строку и отдает строку
- сразу в main эту лямбду и описал

Сначала показалось правильным использовать флаг true/false прямо в классе

2024-08-16 07:05 UTC, ievetrovdev approved these changes
Да, отлично

2024-08-16 12:04 UTC, merged