KS-4-2 Выполнил второе задание 
Hudzone/Hudz.three pull request #18
Opened 2024-02-28 07:10 UTC by Hudzone

2024-02-29 01:17 UTC, ievetrovdev requested changes

2024-02-29 01:17 UTC, ievetrovdev commented on src/main/kotlin/Lesson_4/Task_2.kt
> +    println("Груз весом $weight кг и объемом $volume соответствует категории Average: ${((weight >= 35 && weight <= 100) && volume < 100)}")
Значения в этом коде являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)
не лучшая практика. добавь, пожалуйста, переменные)

И предлагаю переменные с которыми сравниваем входные данные вынести в константы, так как они точно не будут меняться после компиляции

2024-02-29 01:17 UTC, ievetrovdev commented on src/main/kotlin/Lesson_4/Task_2.kt
> +    println("Груз весом $weight кг и объемом $volume соответствует категории Average: ${((weight >= 35 && weight <= 100) && volume < 100)}")
`проверь, соответствуют ли следующие грузы категории "Average": 20 кг / 80 л и 50 кг / 100 л;`

сейчас ты проверяешь только 1 вариант

2024-02-29 07:50 UTC, Hudzone commented
* Попытался для сокращения когда засунуть строку в переменную, но в таком случае логическая конструкция почему то работает не так как нужно

2024-03-01 01:13 UTC, ievetrovdev approved these changes

2024-03-01 01:13 UTC, ievetrovdev commented on src/main/kotlin/Lesson_4/Task_2.kt
> +    println("Груз весом $weight кг и объемом $volume соответствует категории Average: ${((weight >= LOW_EDGE_WEIGHT && weight <= HIGH_EDGE_WEIGHT) && volume < HIGH_EDGE_VOLUME)}")
все хорошо, аппрув)

2024-03-01 01:15 UTC, ievetrovdev commented
> * Попытался для сокращения кода засунуть строку в переменную, но в таком случае логическая конструкция почему то работает не так как нужно

а зачем делать строкой? не работало это из за того что ты хочешь сравнить строку с числом. для того чтобы это исправить тебе нужно было бы строку привести к числу `toInt()`, но смысла это делать в этом задании я не вижу)

2024-03-01 07:42 UTC, merged