KS-4-4 Выполнил четвертое задание 
Hudzone/Hudz.three pull request #20
Opened 2024-03-06 07:41 UTC by Hudzone

2024-03-07 07:53 UTC, ievetrovdev requested changes

2024-03-07 07:53 UTC, ievetrovdev commented on src/main/kotlin/Lesson_4/Task_4.kt
> +const val wholeNum: Int = 2
константы принято называть заглавными буквами с нижними подчеркиваниями) также давай их отделять от функций пустой строкой

2024-03-07 15:19 UTC, Hudzone commented on src/main/kotlin/Lesson_4/Task_4.kt
> +const val wholeNum: Int = 2
Да, спасибо, поправил. Забываю все время про строку, там лейбл акка гита стоит и выглядит как будто строка)

2024-03-12 07:02 UTC, ievetrovdev approved these changes

2024-03-12 08:04 UTC, merged