KS-6-1 Выполнил первое задание
Hudzone/Hudz.three pull request #27
Opened 2024-03-22 07:52 UTC by Hudzone

2024-03-22 14:39 UTC, ievetrovdev requested changes

2024-03-22 14:39 UTC, ievetrovdev commented on src/main/kotlin/Lesson_6/Task_1.kt
> +    var x = 1
а зачем здесь эта переменная?)

2024-03-22 14:39 UTC, ievetrovdev commented on src/main/kotlin/Lesson_6/Task_1.kt
> +    while (true) {
давай вместо бесконечного цикла сделаем условие из `if`
`authLogin != regLogin && authPass != regPass`

2024-03-22 14:50 UTC, Hudzone commented on src/main/kotlin/Lesson_6/Task_1.kt
> +    while (true) {
Да, думал над этим вариантом тоже) Но решил вариант с вайлтру)

2024-03-22 14:50 UTC, Hudzone commented on src/main/kotlin/Lesson_6/Task_1.kt
> +    var x = 1
А сори, я для дебага себе сделал чтобы смотреть что итерации идут, удалю

2024-03-24 06:28 UTC, ievetrovdev approved these changes

2024-03-24 06:29 UTC, ievetrovdev requested changes

2024-03-24 06:29 UTC, ievetrovdev commented on src/main/kotlin/Lesson_6/Task_1.kt
> +        authPass= readln()
давай сделаем автоформатирование кода)

2024-03-24 06:29 UTC, ievetrovdev commented on src/main/kotlin/Lesson_6/Task_1.kt
> +            println("Авторизация прошла успешно")
эту строку можно вынести за цикл

2024-03-24 12:53 UTC, merged