KS-6-2 Выполнил второе задание
Hudzone/Hudz.three pull request #28
Opened 2024-03-24 13:04 UTC by Hudzone

2024-03-25 07:45 UTC, ievetrovdev requested changes

2024-03-25 07:45 UTC, ievetrovdev commented on src/main/kotlin/Lesson_6/Task_2.kt
> +    while (userInput > 0) {
По условию вроде не нужно делать цикл. Может можно обойтись одним вызовом sleep?)

2024-03-25 07:45 UTC, ievetrovdev commented on src/main/kotlin/Lesson_6/Task_2.kt
> +    var userInput: Int = readln().toInt()
и эту переменную можно будет сделать val)

2024-03-25 16:19 UTC, Hudzone commented
Ну в тз не сказано, что прям НЕ ИСПОЛЬЗОВАТЬ цикл :D Поэтому и использовал) 
Поправил

2024-03-26 02:43 UTC, ievetrovdev approved these changes

2024-03-26 07:26 UTC, merged