KS-7-3 Выполнил третье задание
Hudzone/Hudz.three pull request #34
Opened 2024-04-01 08:01 UTC by Hudzone

2024-04-02 06:14 UTC, ievetrovdev requested changes

2024-04-02 06:14 UTC, ievetrovdev commented on src/main/kotlin/Lesson_7/Task_3.kt
> +    for (i in 0..userInput) {
Можно сделать еще проще. Попробуй применить шаг диапазона.

2024-04-02 08:03 UTC, Hudzone commented on src/main/kotlin/Lesson_7/Task_3.kt
> +    for (i in 0..userInput) {
Готово!

2024-04-03 04:47 UTC, ievetrovdev approved these changes

2024-04-03 07:51 UTC, merged