KS-7-5 Выполнил пятое задание
Hudzone/Hudz.three pull request #36
Opened 2024-04-04 08:01 UTC by Hudzone

2024-04-04 17:02 UTC, ievetrovdev requested changes

2024-04-04 17:02 UTC, ievetrovdev commented on src/main/kotlin/Lesson_7/Task_5.kt
> +                val randSym = listOf(charProg.random(),numProg.random(),upCharProg.random())
В данной реализации хоть ты и складываешь все три диапазона в один набор символов, но есть вероятность, что рандомайзер при генерации пароля упустит один или несколько типов символов. 
Стоит изменить подход. Например, сперва добавлять обязательные символы, затем рандомно оставшиеся из общего набора.

2024-04-04 17:02 UTC, ievetrovdev commented on src/main/kotlin/Lesson_7/Task_5.kt
> +                val randSym = listOf(charProg.random(),numProg.random(),upCharProg.random())
также давай сделаем автоформатирование кода

2024-04-04 20:48 UTC, Hudzone commented
@ievetrovdev решил эту проблему добавив новую логику.

Т.е. после генерации пароля, я проверяю, что он содержит 1 строчную букву, 1 заглавную и цифру, если нет - программа перезапускает цикл и генерит новый пароль.

Автоформат прожал, но вроде бы ничего особо не поменялось... Мб что то не так делаю. Судя по прогресс бару процесс автоформатирования выполняется.

2024-04-05 16:08 UTC, ievetrovdev commented
> @ievetrovdev решил эту проблему добавив новую логику.
> 
> Т.е. после генерации пароля, я проверяю, что он содержит 1 строчную букву, 1 заглавную и цифру, если нет - программа перезапускает цикл и генерит новый пароль.
> 
> Автоформат прожал, но вроде бы ничего особо не поменялось... Мб что то не так делаю. Судя по прогресс бару процесс автоформатирования выполняется.

довольно сложный подход получается. представь что эти условия не будут удовлетворяться 10 циклов подряд и время ожидания увеличится соответственно в 10 раз. юзер не захочет пользоваться такой программой) проще будет в начале добавить в пароль по 1 символу из каждого диапазона, а затем добивать оставшиеся символы из общего диапазона

2024-04-05 16:08 UTC, ievetrovdev requested changes

2024-04-05 16:08 UTC, ievetrovdev commented on src/main/kotlin/Lesson_7/Task_5.kt
> +            val lowerCaseExists = password.any { it.isLowerCase() }
описал в комменте

2024-04-05 16:37 UTC, Hudzone commented
> > @ievetrovdev решил эту проблему добавив новую логику.
> > Т.е. после генерации пароля, я проверяю, что он содержит 1 строчную букву, 1 заглавную и цифру, если нет - программа перезапускает цикл и генерит новый пароль.
> > Автоформат прожал, но вроде бы ничего особо не поменялось... Мб что то не так делаю. Судя по прогресс бару процесс автоформатирования выполняется.
> 
> довольно сложный подход получается. представь что эти условия не будут удовлетворяться 10 циклов подряд и время ожидания увеличится соответственно в 10 раз. юзер не захочет пользоваться такой программой) проще будет в начале добавить в пароль по 1 символу из каждого диапазона, а затем добивать оставшиеся символы из общего диапазона

Понял) Сделаю

2024-04-05 16:37 UTC, Hudzone commented on src/main/kotlin/Lesson_7/Task_5.kt
> +            val lowerCaseExists = password.any { it.isLowerCase() }
Понял, сделаю)

2024-04-08 05:36 UTC, ievetrovdev requested changes

2024-04-08 05:36 UTC, ievetrovdev commented on src/main/kotlin/Lesson_7/Task_5.kt
> +                when {
получился довольно сложный код и при этом ты все равно кладешь в пароль символы из общего диапазона) давай его упростим удалив этот `when` и перед циклом `for` добавим в пароль нужные нам символы:
```
password.append(numProg.random())
password.append(charProg.random())
password.append(upCharProg.random())
```

после этого можем добить оставшиеся символы из общего диапазона

2024-04-08 05:36 UTC, ievetrovdev commented on src/main/kotlin/Lesson_7/Task_5.kt
> +                val randSym = listOf(charProg.random(), numProg.random(), upCharProg.random())
зачем нам создавать общий список символов на каждой итерации цикла?

2024-04-08 05:36 UTC, ievetrovdev commented on src/main/kotlin/Lesson_7/Task_5.kt
> +        break
можно перенести этот `break` внутрь `if`, тогда можно будет удалить `continue` если пароль меньше символов чем нам нужно

2024-04-08 09:27 UTC, Hudzone commented on src/main/kotlin/Lesson_7/Task_5.kt
> +                val randSym = listOf(charProg.random(), numProg.random(), upCharProg.random())
Таким образом реализовал возможность вставки рандомного значения, на каждой итерации генерю, потому что если убрать код выше, то у меня сгенерятся значения только 1 раз, и будут повторы в пароле.

2024-04-09 07:01 UTC, ievetrovdev commented on src/main/kotlin/Lesson_7/Task_5.kt
> +                val randSym = listOf(charProg.random(), numProg.random(), upCharProg.random())
можно было сделать до цикла while общий список символов     
`val allChars = charProg + numProg + upCharProg`
а дальше в цикле из него брать рандомное значение

это на будущее, сейчас аппрув)

2024-04-09 07:02 UTC, ievetrovdev approved these changes

2024-04-09 07:22 UTC, merged