KS-9-2 Второе задание выполнено
Hudzone/Hudz.three pull request #43
Opened 2024-04-13 13:51 UTC by Hudzone

2024-04-13 14:31 UTC, ievetrovdev requested changes

2024-04-13 14:31 UTC, ievetrovdev commented on src/main/kotlin/Lesson_9/Task_2.kt
> +    if (userChoice == "да") {
Для сравнения с учетом регистра можно использовать метод сравнения у которого есть свойство ignoreCase, так не нужно будет менять символ в строке

2024-04-15 07:08 UTC, ievetrovdev approved these changes

2024-04-15 07:08 UTC, ievetrovdev commented on src/main/kotlin/Lesson_9/Task_2.kt
> +    val userChoice = readln().lowercase()
Раз ниже сравниваешь с учетом регистра можно было и убрать привидение к регистру

2024-04-15 07:21 UTC, Hudzone commented on src/main/kotlin/Lesson_9/Task_2.kt
> +    val userChoice = readln().lowercase()
Поправил

2024-04-15 07:21 UTC, merged