KS-10-2 Выполнил второе задание
Hudzone/Hudz.three pull request #48
Opened 2024-04-17 09:47 UTC by Hudzone

2024-04-17 15:36 UTC, ievetrovdev requested changes

2024-04-17 15:36 UTC, ievetrovdev commented on src/main/kotlin/Lesson_10/Task_2.kt
> +fun userLogin() : String = readln()
Не нужно создавать метод ради метода, они нужны чтобы уменьшить количество кода, а не увеличить

2024-04-17 15:36 UTC, ievetrovdev commented on src/main/kotlin/Lesson_10/Task_2.kt
> +fun userAuth() {
Это тоже можно сразу в мейне писать

2024-04-17 15:36 UTC, ievetrovdev commented on src/main/kotlin/Lesson_10/Task_2.kt
> +fun credentialValidation(login: String, pass: String) {
А вот этот метод лучше сделать 1 параметра, и переиспользовать для любой строки. Так же изменить название в инфинитив

2024-04-18 07:01 UTC, ievetrovdev requested changes

2024-04-18 07:01 UTC, ievetrovdev commented on src/main/kotlin/Lesson_10/Task_2.kt
> +fun credentialValidation(login: String, pass: String) {
Смотри, если сделать функцию 1 параметра и название validateString, то такую функцию можно применять и для логина и для пароля, так и вообще для любой строки. В этом суть функций, периспользовать один и тот же код как можно чаще

2024-04-18 08:18 UTC, Hudzone commented on src/main/kotlin/Lesson_10/Task_2.kt
> +fun credentialValidation(login: String, pass: String) {
Да, просто когда делал, мне показалось что логин и пароль логичнее сделать отдельными сущностями. :(

2024-04-19 15:47 UTC, ievetrovdev approved these changes

2024-04-19 15:47 UTC, merged