KS-10-5 Выполнил пятое задание
Hudzone/Hudz.three pull request #51
Opened 2024-04-17 19:38 UTC by Hudzone

2024-04-18 07:10 UTC, ievetrovdev requested changes

2024-04-18 07:10 UTC, ievetrovdev commented on src/main/kotlin/Lesson_10/Task_5.kt
> +fun createJWT(
Функция должна делать то как ее назвали, у тебя функция должна только создать токен, а не заниматься еще и проверкой логина пароля, это лучше вынести за функцию.
Вообще старайся делать функцию одного действия (только сгенерировать пароль или только проверить логин пароль)

2024-04-18 07:10 UTC, ievetrovdev commented on src/main/kotlin/Lesson_10/Task_5.kt
> +fun getCart(jwtToken: String) {
тут та же проблема

2024-04-18 20:44 UTC, Hudzone commented
Вынес функционал валидации для лог/пасса и для токена в отдельные функции

2024-04-19 15:46 UTC, ievetrovdev requested changes

2024-04-19 15:46 UTC, ievetrovdev commented on src/main/kotlin/Lesson_10/Task_5.kt
> +    if (validationStatus) {
Лучше, но опять же эта функция не должна проверять статус, а только создать пароль, проверку же можно вынести в мейн. Так даже если понадобиться обновить токен, можно будет переиспользовать эту функцию(а вариация в таком случае не нужна)

2024-04-19 15:46 UTC, ievetrovdev commented on src/main/kotlin/Lesson_10/Task_5.kt
> +fun getCart(tokenStatus: Boolean) {
В данном случае название не подходит действию функции, printCart больше подходит

2024-04-20 06:01 UTC, ievetrovdev approved these changes

2024-04-20 13:00 UTC, merged