KS-1-5 Выполнил пятое задание
Hudzone/Hudz.three pull request #6
Opened 2024-02-16 13:24 UTC by Hudzone

2024-02-17 10:43 UTC, ievetrovdev requested changes
Кроме того, тут ошибка в расчетах, результат должен быть такой [01:48:00], попробуй сначала произвести вычисления, а String.format() изпользовать уже для вывода

2024-02-17 10:43 UTC, ievetrovdev commented on src/main/kotlin/Lesson_1/Task_5.kt
> +    val fullMinutes: Int = fullSeconds / 60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

2024-02-17 10:43 UTC, ievetrovdev commented on src/main/kotlin/Lesson_1/Task_5.kt
> +    val hours: Float = fullSeconds / 3600F
Значения в этом коде являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F). Не лучшая практика. Предлагаю добавить переменные)

2024-02-17 10:43 UTC, ievetrovdev commented on src/main/kotlin/Lesson_1/Task_5.kt
> +    val counting: Float = seconds / 100F
Еще одно [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), человек первый раз увидевший код, не поймет о чем тут речь

2024-02-17 16:53 UTC, Hudzone commented
Избавился от магических чисел, и улучшил реализацию, мб излишне, но если потом эту программу отрефакторить (поменять val на var и т.д.), и работать с любым значением секунд - все будет работать

2024-02-18 09:41 UTC, ievetrovdev approved these changes
Решение рабочее, это задача повышенной сложности ("со звездочкой") не по уровню урока, требует дополнительного ресерча).

Давай на будущее комментированный код не оставлять, если на это нет действительно веских причин.

2024-02-18 10:36 UTC, merged