KS-13-2 Второе задание выполнено
Hudzone/Hudz.three pull request #64
Opened 2024-07-19 10:59 UTC by Hudzone

2024-07-19 13:13 UTC, ievetrovdev requested changes

2024-07-19 13:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/Task_2.kt
> +    val company: String = null ?: "<не указано>"
Это плохая идея, ты перезаписываешь поле company на значение "<не указано>", и теперь не понятно - это компания так называется или оно и правда не указано.
В дальнейшем если решишь расширять логику приложения, например, вывести все контакты в которых не указана компания, столкнешься с проблемой.
Лучше при печати проверять поле не меняя, попробуй оператор elvis ( ?: )

2024-07-19 14:37 UTC, Hudzone commented on src/main/kotlin/lesson_13/Task_2.kt
> +    val company: String = null ?: "<не указано>"
@ievetrovdev да, просто в задаче было указано, что значение по умолчанию должно быть null, поэтому решил вот так вот реализовать. Поправлю, спасибо!

2024-07-20 14:08 UTC, ievetrovdev approved these changes

2024-07-20 15:12 UTC, merged