KS-2-1 Выполнил первое задание
Hudzone/Hudz.three pull request #7
Opened 2024-02-18 10:42 UTC by Hudzone

2024-02-18 15:54 UTC, ievetrovdev requested changes

2024-02-18 15:54 UTC, ievetrovdev commented on src/main/kotlin/Lesson_2/Task_1.kt
> +    var sum = 0
Раз уж используешь массив, то можно воспользоваться функцией sum

2024-02-18 15:54 UTC, ievetrovdev commented on src/main/kotlin/Lesson_2/Task_1.kt
> +    val quantity = studentsResult.size
Нет необходимости для размера создавать отдельную переменную, все равно используешь ее только 1 раз. Так ты только усложняешь чтение кода

2024-02-18 16:10 UTC, Hudzone commented
Внес изменения согласно комментариям

2024-02-19 07:10 UTC, ievetrovdev approved these changes
Да, отлично

2024-02-19 08:06 UTC, merged