KS-14-3 Третье задание выполнено
Hudzone/Hudz.three pull request #70
Opened 2024-07-21 14:56 UTC by Hudzone

2024-07-21 21:28 UTC, ievetrovdev requested changes

2024-07-21 21:28 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/Task_3.kt
> +    val pi: Double = PI_NUM,
Выглядит так будто у pi может быть иное значение, кроме как PI_NUM, но это же не так, верно?

2024-07-21 21:28 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/Task_3.kt
> +abstract class Figure {
Лучше Figure(val color: String), чем прописывать поле. В рамках данной задачи

2024-07-22 10:44 UTC, Hudzone commented on src/main/kotlin/lesson_14/Task_3.kt
> +    val pi: Double = PI_NUM,
Мне тут как раз показалось, что константой и показываю, что значение одно)

2024-07-22 20:54 UTC, ievetrovdev requested changes

2024-07-22 20:54 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/Task_3.kt
> +    val pi: Double = 3.14,
Pi должно быть как и const val DEFAULT_MULTIPLIER реализовано, и его использование в классе такое же, не нужно под него поле, это лишнее дублирование

2024-07-22 20:54 UTC, ievetrovdev requested changes

2024-07-22 20:54 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/Task_3.kt
> +
Давай не будем оставлять более одной пустой строки

2024-07-22 21:15 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-07-24 10:24 UTC, merged