KS-15-3 Третье задание выполнено
Hudzone/Hudz.three pull request #75
Opened 2024-07-26 17:09 UTC by Hudzone

Некий сумбур получился, но было весело)

2024-07-27 15:05 UTC, ievetrovdev requested changes

2024-07-27 15:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/Task_3.kt
> +interface ForumBaseActions {
В условии сказано использовать абстрактный класс для сущностей юзера и администратора, давай этот интерфейс заменим на него)

2024-07-27 15:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/Task_3.kt
> +    fun send(address: Forum, author: ForumBaseActions = this, message: String)
Здесь автор ссылается сам на себя? Странно выглядит логика)

2024-07-27 15:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/Task_3.kt
> +) {}
Пустые скобки класса можно опустить

2024-07-27 15:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/Task_3.kt
> +open class User(
А зачем этот класс open? Мы же нигде не наследуемся от него)

2024-07-27 15:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/Task_3.kt
> +    lyoha.send(balabolnya, message = "А еще я удалю тебя Борька, и твое сообщение Васян! Тред закрт))))))")
Сообщения топ))

2024-07-27 18:18 UTC, Hudzone commented on src/main/kotlin/lesson_15/Task_3.kt
> +open class User(
Это я сначала другую реализацию пилил, и забыл видимо open убрать

2024-07-28 09:51 UTC, ievetrovdev approved these changes

2024-07-29 08:25 UTC, merged