KS-16-2 Второе задание выполнено
Hudzone/Hudz.three pull request #79
Opened 2024-07-29 18:14 UTC by Hudzone

2024-07-30 07:38 UTC, ievetrovdev requested changes

2024-07-30 07:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/Task_2.kt
> +    val radius: Double,
Прочитай ТЗ внимательнее
Радиус передается через конструктор и не виден из внешнего по отношению к классу кода

2024-07-30 07:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/Task_2.kt
> +    private val pi: Double = 3.14
Давай еще сделаем ее const, тк это все таки постоянное число.

2024-07-30 17:26 UTC, Hudzone commented on src/main/kotlin/lesson_16/Task_2.kt
> +    private val pi: Double = 3.14
Сделал отдельной константой в файле, с private оно не работает, плюс в ТЗ вроде написано что эта функция не должна быть видна... Но тогда противоречие

2024-07-31 07:13 UTC, ievetrovdev requested changes
private const val PI = 3.14
Просто можно вынести из класса

2024-07-31 07:13 UTC, ievetrovdev approved these changes

2024-08-01 17:49 UTC, merged