KS-18-1 Первое задание выполнено
Hudzone/Hudz.three pull request #88
Opened 2024-08-03 16:40 UTC by Hudzone

2024-08-05 18:08 UTC, ievetrovdev requested changes

2024-08-05 18:08 UTC, ievetrovdev commented on src/main/kotlin/lesson_18/Task_1.kt
> +    private val items: String,
В Kotlin, список может содержать  любое количество элементов, включая один элемент. Поэтому лучше инициализировать переменную как список (List)

2024-08-05 18:08 UTC, ievetrovdev commented on src/main/kotlin/lesson_18/Task_1.kt
> +    fun printItems() {
Здесь у тебя просто два разных метода. В ТЗ сказано, что задачу требуется решить полиморфизмом с типом ad hoc. Напомню, он реализуется с помощью перегрузки методов с одинаковой сигнатурой (и соответственно названием).

2024-08-05 18:08 UTC, ievetrovdev commented on src/main/kotlin/lesson_18/Task_1.kt
> +
В целом это пока довольно базовые задачи. Продвинутыми способами решать не запрещается, но хочу обратить внимание, что не стоит усложнять ради усложнения. Такой подход на реальной практике сыграет злую шутку. Там, где можно сделать проще – лучше сделать проще, но в рамках ТЗ.

2024-08-05 18:09 UTC, ievetrovdev requested changes

2024-08-05 18:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_18/Task_1.kt
> +
Больше одной пустой строки оставлять не рекомендую.

2024-08-06 07:19 UTC, ievetrovdev requested changes
В целом это пока довольно базовые задачи. Продвинутыми способами решать не запрещается, но хочу обратить внимание, что не стоит усложнять ради усложнения. Такой подход на реальной практике сыграет злую шутку. Там, где можно сделать проще – лучше сделать проще, но в рамках ТЗ.

2024-08-06 19:08 UTC, Hudzone commented
Не знал как сделать проще код, сократить. Нашел в доке инфу про обобощенный класс, попробовал так сделать

2024-08-06 20:10 UTC, ievetrovdev approved these changes
Очень хорошее решение, двигаемся дальше

2024-08-06 20:21 UTC, merged